//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Details_Commande
    {
        public int IdDetail { get; set; }
        public int Id_Commande { get; set; }
        public int Id_Produit { get; set; }
        public string NomProduit { get; set; }
        public int Quantite { get; set; }
        public string Prix { get; set; }
        public string Remise { get; set; }
        public string Total { get; set; }
    
        public virtual COMMANDE COMMANDE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
