//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class PANIER
    {
        public int Id_Ligne_Panier { get; set; }
        public int Id_Produit { get; set; }
        public int Id_Client { get; set; }
        public int Quantite { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
    }
}
