use ERP_Gestion_Stock
--création des tables--
CREATE TABLE CATEGORIE(
   Id_CATEGORIE INT NOT NULL,
   Nom VARCHAR(50) NOT NULL,
   Nature VARCHAR(15),
   PRIMARY KEY(Id_CATEGORIE)
);

CREATE TABLE FOURNISSEUR(
   Id_FOURNISSEUR INT NOT NULL,
   Nom VARCHAR(50),
   Rue VARCHAR(200),
   CodePostal INT,
   Ville VARCHAR(25),
   Pays VARCHAR(20),
   Email VARCHAR(50),
   Telephone VARCHAR(15),
   Num_Siret VARCHAR(15),
   Num_TVA VARCHAR(15),
   PRIMARY KEY(Id_FOURNISSEUR)
);

CREATE TABLE CMD_CLIENT(
   Id_CmdClient INT NOT NULL,
   DateCommande DATE,
   LibelleCommande VARCHAR(200),
   DateLivraison DATE,
   Montant_cmd DECIMAL(15,2),
   Etat_cmd VARCHAR(25),
   LieuLivraison_cmd VARCHAR(50),
   Mode_Paiement VARCHAR(10),
   Devise VARCHAR(10),
   PRIMARY KEY(Id_CmdClient)
);

CREATE TABLE FACTURE(
   Id_FACTURE INT NOT NULL,
   LibelleFacture VARCHAR(50),
   MontantFacture DECIMAL(15,2),
   DateFacture DATETIME,
   Id_CmdClient INT NOT NULL,
   PRIMARY KEY(Id_FACTURE),
   FOREIGN KEY(Id_CmdClient) REFERENCES CMD_CLIENT(Id_CmdClient)
);

CREATE TABLE EMPLOYE(
   Id_UTILISATEUR INT NOT NULL,
   Nom VARCHAR(50),
   Prénom VARCHAR(50),
   Rôle VARCHAR(20),
   PRIMARY KEY(Id_UTILISATEUR)
);

CREATE TABLE EMPLACEMENT_STOCK(
   Id_EMPLACEMENT INT NOT NULL,
   NumRang VARCHAR(5),
   NumCasier VARCHAR(5),
   PRIMARY KEY(Id_EMPLACEMENT)
);

CREATE TABLE CMD_FOURNISSEUR(
   Id_CmdClient INT NOT NULL,
   LibelleCommande VARCHAR(200),
   DateCommande DATE,
   DateLivraison DATE,
   Montant_cmde DECIMAL(15,2),
   Mode_Paiement VARCHAR(10),
   Prix_achatHT DECIMAL(15,2),
   Taxe DECIMAL(15,2),
   MontantCmd DECIMAL(15,2),
   PRIMARY KEY(Id_CmdClient)
);

CREATE TABLE UTILISATEUR(
   NomUtilisateur VARCHAR(50),
   Mot_de_Passe VARCHAR(50),
   Id_UTILISATEUR INT NOT NULL,
   PRIMARY KEY(NomUtilisateur),
   UNIQUE(Id_UTILISATEUR),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR)
);

CREATE TABLE ARTICLE(
   Id_ARTICLE VARCHAR(18),
   Nom VARCHAR(50) NOT NULL,
   Description VARCHAR(250),
   Image_Produit VARBINARY,
   Note DECIMAL(2,2),
   Cepage VARCHAR(50),
   Annee DATE,
   Prix_Produit DECIMAL(15,2) NOT NULL,
   Taxe_Pduit DECIMAL(15,2),
   Quantité_dispo DECIMAL(15,2),
   Id_CATEGORIE INT NOT NULL,
   PRIMARY KEY(Id_ARTICLE),
   FOREIGN KEY(Id_CATEGORIE) REFERENCES CATEGORIE(Id_CATEGORIE)
);

CREATE TABLE CLIENT(
   Id_CLIENT INT NOT NULL,
   Nom VARCHAR(50),
   Prénom VARCHAR(50),
   Rue VARCHAR(200),
   Code_Postal INT,
   Ville VARCHAR(25),
   Pays VARCHAR(20),
   Email VARCHAR(50),
   Telephone VARCHAR(15),
   Num_Siret VARCHAR(15),
   Num_TVA VARCHAR(15),
   Id_CmdClient INT NOT NULL,
   PRIMARY KEY(Id_CLIENT),
   FOREIGN KEY(Id_CmdClient) REFERENCES CMD_CLIENT(Id_CmdClient)
);

CREATE TABLE Receptionner(
   Id_ARTICLE VARCHAR(18),
   Id_CmdClient INT,
   Entrée_Stock DECIMAL(15,0),
   Prix_achat VARCHAR(50),
   PRIMARY KEY(Id_ARTICLE, Id_CmdClient),
   FOREIGN KEY(Id_ARTICLE) REFERENCES ARTICLE(Id_ARTICLE),
   FOREIGN KEY(Id_CmdClient) REFERENCES CMD_FOURNISSEUR(Id_CmdClient)
);

CREATE TABLE Livrer(
   Id_FOURNISSEUR INT,
   Id_CmdClient INT,
   PRIMARY KEY(Id_FOURNISSEUR, Id_CmdClient),
   FOREIGN KEY(Id_FOURNISSEUR) REFERENCES FOURNISSEUR(Id_FOURNISSEUR),
   FOREIGN KEY(Id_CmdClient) REFERENCES CMD_FOURNISSEUR(Id_CmdClient)
);

CREATE TABLE Correspondre(
   Id_ARTICLE VARCHAR(18),
   Id_CmdClient INT,
   Prix_Vente DECIMAL(15,2),
   Sortie_Stock DECIMAL(15,0),
   PRIMARY KEY(Id_ARTICLE, Id_CmdClient),
   FOREIGN KEY(Id_ARTICLE) REFERENCES ARTICLE(Id_ARTICLE),
   FOREIGN KEY(Id_CmdClient) REFERENCES CMD_CLIENT(Id_CmdClient)
);

CREATE TABLE Editer(
   Id_FACTURE INT,
   Id_UTILISATEUR INT,
   PRIMARY KEY(Id_FACTURE, Id_UTILISATEUR),
   FOREIGN KEY(Id_FACTURE) REFERENCES FACTURE(Id_FACTURE),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR)
);

CREATE TABLE Contenir(
   Id_ARTICLE VARCHAR(18),
   Id_EMPLACEMENT INT,
   PRIMARY KEY(Id_ARTICLE, Id_EMPLACEMENT),
   FOREIGN KEY(Id_ARTICLE) REFERENCES ARTICLE(Id_ARTICLE),
   FOREIGN KEY(Id_EMPLACEMENT) REFERENCES EMPLACEMENT_STOCK(Id_EMPLACEMENT)
);

CREATE TABLE Organiser(
   Id_UTILISATEUR INT,
   Id_EMPLACEMENT INT,
   PRIMARY KEY(Id_UTILISATEUR, Id_EMPLACEMENT),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR),
   FOREIGN KEY(Id_EMPLACEMENT) REFERENCES EMPLACEMENT_STOCK(Id_EMPLACEMENT)
);

CREATE TABLE Inscrire(
   Id_CLIENT INT,
   Id_UTILISATEUR INT,
   PRIMARY KEY(Id_CLIENT, Id_UTILISATEUR),
   FOREIGN KEY(Id_CLIENT) REFERENCES CLIENT(Id_CLIENT),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR)
);

CREATE TABLE Créer(
   Id_FOURNISSEUR INT,
   Id_UTILISATEUR INT,
   PRIMARY KEY(Id_FOURNISSEUR, Id_UTILISATEUR),
   FOREIGN KEY(Id_FOURNISSEUR) REFERENCES FOURNISSEUR(Id_FOURNISSEUR),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR)
);

CREATE TABLE Enregistrer(
   Id_ARTICLE VARCHAR(18),
   Id_UTILISATEUR INT,
   PRIMARY KEY(Id_ARTICLE, Id_UTILISATEUR),
   FOREIGN KEY(Id_ARTICLE) REFERENCES ARTICLE(Id_ARTICLE),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR)
);

CREATE TABLE Réaliser(
   Id_UTILISATEUR INT,
   Id_CmdClient INT,
   PRIMARY KEY(Id_UTILISATEUR, Id_CmdClient),
   FOREIGN KEY(Id_UTILISATEUR) REFERENCES EMPLOYE(Id_UTILISATEUR),
   FOREIGN KEY(Id_CmdClient) REFERENCES CMD_FOURNISSEUR(Id_CmdClient)
);
